eureka:
  client:
    service-url:
      defaultZone: http://pubinfo:zhly@172.10.1.101:8011/eureka/,http://pubinfo:zhly@172.10.1.136:8011/eureka/

spring:
  datasource:
    url: jdbc:mysql://172.10.2.119:3306/unit?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&useSSL=false
    username: root
    password: Smart2018@travel
  rabbitmq:
    host: 172.10.1.101
    username: pubinfo
    password: zhlyrabbit

security:
  oauth2:
    resource:
      token-info-uri: http://172.10.1.136:12306/oauth/oauth/check_token

pubinfo:
  oauth2:
    allow-all-request: true
