eureka:
  client:
    service-url:
      defaultZone: http://pubinfo:zhly@192.168.1.116:8011/eureka/

spring:
  rabbitmq:
    host: 192.168.1.116
    username: pubinfo
    password: zhly
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: zck123
    url: jdbc:mysql://192.168.1.116:3306/user?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&useSSL=false

security:
  oauth2:
    resource:
      token-info-uri: http://192.168.1.116/oauth/oauth/check_token

pubinfo:
  oauth2:
    allow-all-request: true
