eureka:
  client:
    service-url:
      defaultZone: http://pubinfo:zhly@192.168.1.116:8011/eureka/
    register-with-eureka: test1dev
    enabled: false

spring:
  rabbitmq:
    host: 192.168.1.116
    username: pubinfo
    password: zhly
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Smart2018@travel
    url: jdbc:mysql://192.168.30.43:3306/unit?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&useSSL=false

security:
  oauth2:
    resource:
      token-info-uri: http://192.168.1.116/oauth/oauth/check_token

logging:
  level:
    cn.pubinfo: debug

pubinfo:
  oauth2:
    allow-all-request: true
info:
    test: version_test1
